server:
  port: 8080

spring:
  main: web-application-type:reactive
  application:
    name: APIGATEWAY-SERVICE  
  cloud:
    gateway:
      routes:
        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/stockExchange/**
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/company/**
        - id: excel-service
          uri: lb://excel-service
          predicates:
            - Path=/excel/**
        - id: sector-service
          uri: lb://sector-service
          predicates:
            - Path=/sectors/**
